name: Pest / PHPUnit (Laravel)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  laravel-tests:
    name: Laravel PHPUnit/Pest
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: bagisto_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: mbstring, exif, pcntl, bcmath, intl, pdo_mysql
          coverage: none

      - name: Copy .env
        run: cp .env.example .env

      - name: Configure DB env
        run: |
          php -r "file_put_contents('.env', preg_replace('/^DB_DATABASE=.*/m', 'DB_DATABASE=bagisto_test', file_get_contents('.env')));"
          php -r "file_put_contents('.env', preg_replace('/^DB_USERNAME=.*/m', 'DB_USERNAME=root', file_get_contents('.env')));"
          php -r "file_put_contents('.env', preg_replace('/^DB_PASSWORD=.*/m', 'DB_PASSWORD=root', file_get_contents('.env')));"

      - name: Install Composer deps
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: App key & migrate
        run: |
          php artisan key:generate
          php artisan migrate --force

      - name: Run backend tests
        run: |
          if [ -f vendor/bin/pest ]; then
            vendor/bin/pest -q
          else
            php artisan test --no-interaction --env=testing
          fi
